import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/modules/landing/header";
import { Footer } from "@/modules/landing/footer";
import { Navbar } from "@/modules/landing/navbar";
import { LiveRatePopup } from "@/modules/live-rates/live-rates-popup";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <Header />
          <Navbar />
          {children}
          <LiveRatePopup />
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
