import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/modules/landing/header";
import { Footer } from "@/modules/landing/footer";
import { Navbar } from "@/modules/landing/navbar";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";
import { Raleway } from "next/font/google";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} antialiased font-(--font-raleway) bg-black`}
      >
        <ReactQueryProvider>
          <Header />
          <Navbar />
          {children}
          {/* <LiveRatePopup /> */}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
