import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/modules/landing/header";
import { Footer } from "@/modules/landing/footer";
import { Navbar } from "@/modules/landing/navbar";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";
import { Toaster } from "@/components/ui/sonner";
import { geistMono, geistSans } from "@/utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-black`}
      >
        <ReactQueryProvider>
          <Header />
          <Navbar />
          {children}
          {/* <LiveRatePopup /> */}
          <Footer />
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
